name: deploy

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: wasm-pack-action
        uses: jetli/wasm-pack-action@v0.3.0
        with: 'latest'
      - name: rust-cargo
        uses: actions/checkout@v2
        uses: actions-rs/toolchain@v1
        with: 
          toolchain: nigitly
      - run: cargo install miniserve
      - run: cargo release
      - uses: peaceiris/actions-gh-pages@v2.4.0
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/deploy