name: deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
        
      - name: wasm-pack build
        run: wasm-pack build --target web --out-name wasm --out-dir /home/runner/work/yew-portfolio/yew-portfolio/static
      
      - name: install nightly
        uses: actions-rs/toolchain@v1
        with: 
          toolchain: nightly
          override: true

      - name: install cargo-release
        run: cargo install cargo-release
      
      - name: install miniserve
        run: cargo install miniserve

      - name: release
        run: cargo release
      
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.4.0
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/deploy